import Navbar from "@/components/navbar";
import Footer from "@/components/footer";

export default function FeaturesPage() {
  return (
    <main className="min-h-screen">
      <Navbar />
      <div className="container mx-auto px-4 py-20">
        <h1 className="text-5xl font-extrabold mb-6 gradient-text-secondary text-center">
          Features
        </h1>
        <p className="text-xl text-center text-slate-300 max-w-3xl mx-auto mb-12">
          Discover all the powerful features that PATHLY offers to make your
          roads safer and travel more efficient. Our platform is designed to
          help drivers and authorities alike by providing real-time data, smart
          analysis, and reliable insights.
        </p>

        <section className="max-w-5xl mx-auto grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-12">
          <div className="feature-card bg-blue-900/30 p-6 rounded-lg shadow-lg hover:shadow-2xl transition-shadow duration-300">
            <h3 className="text-2xl font-semibold mb-3">
              Real-time Road Quality Monitoring
            </h3>
            <p className="text-slate-400">
              Using IoT sensors installed on vehicles, PATHLY continuously
              collects data about road conditions, allowing instant detection of
              potholes, cracks, and other hazards.
            </p>
          </div>

          <div className="feature-card bg-blue-900/30 p-6 rounded-lg shadow-lg hover:shadow-2xl transition-shadow duration-300">
            <h3 className="text-2xl font-semibold mb-3">
              Accurate Travel Time Estimation
            </h3>
            <p className="text-slate-400">
              PATHLY calculates expected travel times between multiple points
              based on current traffic and road conditions, helping you plan
              your journey better and avoid delays.
            </p>
          </div>

          <div className="feature-card bg-blue-900/30 p-6 rounded-lg shadow-lg hover:shadow-2xl transition-shadow duration-300">
            <h3 className="text-2xl font-semibold mb-3">
              User-Friendly Dashboard
            </h3>
            <p className="text-slate-400">
              Our intuitive dashboard visualizes road quality metrics, travel
              analytics, and alerts, enabling both users and city planners to
              make informed decisions quickly.
            </p>
          </div>

          <div className="feature-card bg-blue-900/30 p-6 rounded-lg shadow-lg hover:shadow-2xl transition-shadow duration-300">
            <h3 className="text-2xl font-semibold mb-3">
              Custom Alerts & Notifications
            </h3>
            <p className="text-slate-400">
              Receive timely alerts about road maintenance needs or unexpected
              traffic issues, helping you stay safe and avoid troublesome
              routes.
            </p>
          </div>

          <div className="feature-card bg-blue-900/30 p-6 rounded-lg shadow-lg hover:shadow-2xl transition-shadow duration-300">
            <h3 className="text-2xl font-semibold mb-3">
              Data-Driven Maintenance Planning
            </h3>
            <p className="text-slate-400">
              Authorities can leverage detailed reports generated by PATHLY to
              prioritize repairs and optimize budget allocation for road
              maintenance projects.
            </p>
          </div>

          <div className="feature-card bg-blue-900/30 p-6 rounded-lg shadow-lg hover:shadow-2xl transition-shadow duration-300">
            <h3 className="text-2xl font-semibold mb-3">
              Seamless Integration with Navigation Apps
            </h3>
            <p className="text-slate-400">
              PATHLY integrates smoothly with popular navigation systems to
              provide enhanced routing options based on up-to-date road quality
              and traffic information.
            </p>
          </div>
        </section>

        <div className="text-center mt-16">
          <a
            href="#"
            className="bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors duration-300 font-bold px-8 py-4 rounded-full hover:scale-105 transition-transform duration-300"
          >
            Get Started with PATHLY
          </a>
        </div>
      </div>
      <Footer />
    </main>
  );
}
